const ActionTypes = {
    ADD_PROJECT: 'ADD_PROJECT',
    EDIT_PROJECT: 'EDIT_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    STEP_NEXT_PROJECT: 'STEP_NEXT_PROJECT',

    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    CLOSE_SNACKBAR: 'CLOSE_SNACKBAR'
}

export default ActionTypes; 