const ActionTypes = {
    SET_LOADING: 'SET_LOADING',

    ADD_PROJECT: 'ADD_PROJECT',
    EDIT_PROJECT: 'EDIT_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    STEP_NEXT_PROJECT: 'STEP_NEXT_PROJECT',
    FETCH_PROJECTS: 'FETCH_PROJECTS', 
    UPDATE_PROJECT: 'UPDATE_PROJECT',

    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',

    FETCH_DATA: 'FETCH_DATA',
    UPLOAD_DATA: 'UPLOAD_DATA'
}

export default ActionTypes; 